spring:
  datasource:
    url: jdbc:h2:~/db/htt;AUTO_SERVER=TRUE;OLD_INFORMATION_SCHEMA=TRUE;DATABASE_TO_LOWER=TRUE
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:create_schema.sql
  profiles:
    active: view